// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWiazUhCIg5h1pkrFbUgQR_p_g7gvGzZo',
    appId: '1:770714286776:web:7f8c3e4365a757faa7124d',
    messagingSenderId: '770714286776',
    projectId: 'auto-mates-e8ebe',
    authDomain: 'auto-mates-e8ebe.firebaseapp.com',
    storageBucket: 'auto-mates-e8ebe.appspot.com',
    measurementId: 'G-JV1M60EVTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxTgAxXvp4rigj3sZk_8uxRkpQiJsCnfc',
    appId: '1:770714286776:android:9a32b704e6264bb2a7124d',
    messagingSenderId: '770714286776',
    projectId: 'auto-mates-e8ebe',
    storageBucket: 'auto-mates-e8ebe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF-Cbl6RihIb-mdOGM1q8C_moODhETQKM',
    appId: '1:770714286776:ios:cd330664b80d3a92a7124d',
    messagingSenderId: '770714286776',
    projectId: 'auto-mates-e8ebe',
    storageBucket: 'auto-mates-e8ebe.appspot.com',
    iosBundleId: 'com.example.autoMates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF-Cbl6RihIb-mdOGM1q8C_moODhETQKM',
    appId: '1:770714286776:ios:cd330664b80d3a92a7124d',
    messagingSenderId: '770714286776',
    projectId: 'auto-mates-e8ebe',
    storageBucket: 'auto-mates-e8ebe.appspot.com',
    iosBundleId: 'com.example.autoMates',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWiazUhCIg5h1pkrFbUgQR_p_g7gvGzZo',
    appId: '1:770714286776:web:1646959daa5868f9a7124d',
    messagingSenderId: '770714286776',
    projectId: 'auto-mates-e8ebe',
    authDomain: 'auto-mates-e8ebe.firebaseapp.com',
    storageBucket: 'auto-mates-e8ebe.appspot.com',
    measurementId: 'G-FWT6EBC4N5',
  );
}
